# ════════════════════════════════════════════════════════════════
# Spring Cleaning Plan — generated by spring_clean
# REVIEW CAREFULLY before running.
# This script MOVES files to a trash folder — nothing is permanently deleted.
#
# Usage:  powershell -ExecutionPolicy Bypass -File spring_clean_plan.ps1
# ════════════════════════════════════════════════════════════════

$TrashDir = "$env:USERPROFILE\Desktop\spring_clean_trash_20260412_222353"
Write-Host "Creating trash folder: $TrashDir"
New-Item -ItemType Directory -Force -Path $TrashDir | Out-Null

# ── DELETE NOW (high confidence) ─────────────────────────────────────
$Moved = 0; $Errors = 0


Write-Host ""
Write-Host "Done!  Moved $Moved files, $Errors errors."
Write-Host "Trash folder: $TrashDir"
Write-Host "Permanently delete when satisfied: Remove-Item $TrashDir -Recurse -Force"

# ── REVIEW (open folders manually) ──────────────────────────────────