study_name: "window-study-4w"
symbol: "XAUUSD"
timeframe: "M15"

ea_name: "ZGB5_v14_3"
ea_path: "ZGB5_v14_3"
base_set_path: "configs/sets/study_window_params.set"
mt5_terminal_path: "C:/Program Files/Vantage International MT5/terminal64.exe"
mt5_login: 18912087
mt5_server: "VantageInternational-Live 3"
output_root: "./output/window_study_4w"

windows_weeks: [4]
study_start: "2025-12-06"
study_end: "2026-02-28"
step_weeks: 2
forward_weeks: 2
deposit: 10000000
